[project]
name = "pythonspaceshooter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ps-Dxrk", email = "aaronpaul908070@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pygame-ce>=2.5.8",
]

[project.scripts]
pythonspaceshooter = "pythonspaceshooter:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
